# Generated by Django 3.0 on 2020-01-15 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Jefactura ISC', 'Jefactura ISC'), ('Secretaria', 'Secretaria'), ('Jefactura de Docencia', 'Jefactura de Docencia'), ('Jefactura de Vinculacion', 'Jefactura de Vinculacion'), ('Jefactura de Investigacion', 'Jefactura de Investigacion'), ('Jefactura de Laboratorio', 'Jefactura de Laboratorio'), ('Docentes', 'Docentes')], max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
